allowlist:
  - localhost
  - 127.0.0.1
  - ::1
  - localhost:3001

title: My Awesome Homepage
theme: dark
color: slate
background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
