- Developer:
    - Github:
        - icon: github
          href: https://github.com/
    - ChatGPT:
        - icon: message-square
          href: https://chat.openai.com/

- Social:
    - Reddit:
        - icon: reddit
          href: https://reddit.com/
    - Twitter:
        - icon: twitter
          href: https://twitter.com/

- Entertainment:
    - YouTube:
        - icon: youtube
          href: https://youtube.com/
    - Netflix:
        - icon: netflix
          href: https://netflix.com/

- Work:
    - Podio:
        - icon: podio
          href: https://podio.com/home
    - Curanet:
        - icon: cloud
          href: https://reseller.curanet.dk/Subscription
    - ManageWP:
        - icon: managewp
          href: https://managewp.com/
    - SharePoint:
        - icon: microsoftsharepoint
          href: https://brandbyhand.sharepoint.com/sites/brandbyhand/Delte%20dokumenter/Forms/AllItems.aspx
    - Freshdesk:
        - icon: freshdesk
          href: https://brandbyhand.freshdesk.com/support/login
