- Developer:
    - Github:
        - icon: github
          href: https://github.com/
    - ChatGPT:
        - icon: message-square
          href: https://chat.openai.com/

- Social:
    - Reddit:
        - icon: reddit
          href: https://reddit.com/
    - Twitter:
        - icon: twitter
          href: https://twitter.com/

- Entertainment:
    - YouTube:
        - icon: youtube
          href: https://youtube.com/
    - Netflix:
        - icon: netflix
          href: https://netflix.com/